name: .net ci workflow

on:
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: src

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install project dependencies
      run:
        dotnet restore
    - name: Execute tests and generate coverage report
      run: dotnet test -l "console;verbosity=detailed"
    - name: Build project
      run: dotnet build --configuration Release --no-restore